name: Docker Image CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 00 1/14 * *'
jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ksponomarev -p "$TOKEN"
      env:
        TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ksponomarev/builder:latest
    - name: Push the image to Docker hub
      run: docker push ksponomarev/builder:latest
